/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:825b4bf0-bb2f-4d1f-ad7d-fbb57a97461d",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_ufDVMSjv9",
    "aws_user_pools_web_client_id": "2lmf2mgludt1f4fq5v1rh26ihh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://pi72ghogenafxersw7ozt6uxja.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-qbrty7rcxrdb3lhtpclpatjugy",
    "aws_user_files_s3_bucket": "memoapp-bucket-demo52612-dev",
    "aws_user_files_s3_bucket_region": "ap-northeast-1"
};


export default awsmobile;
